# Generated by Django 5.0.2 on 2024-02-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_marks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
