# Generated by Django 5.0.2 on 2024-02-19 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_delete_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=5)),
                ('maths', models.CharField(max_length=5)),
                ('science', models.CharField(max_length=5)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='new_app.student')),
            ],
        ),
    ]
